[project]
name = "windows-wallpaper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pillow>=12.0.0",
    "tkcalendar>=1.6.1",
    "ttkthemes>=3.2.2",
]
